version: '3'
services:
  web:
    image: codenames-backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - firestore
    command: bash run_local.sh
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=local-codenames

  node:
    image: codenames-frontend:local
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web
    command: bash run_local.sh

  firestore:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=local-codenames
      - PORT=8200
